### ISSUE TITLE
Declare cargo raze in dependencies

### ISSUE THREAD

**Issue by lolski** [vaticle/dependencies#332] opened 2021-12-09 11:43 UTC
Currently our developers have to install Cargo Raze using `cargo`. This isn't ideal and the better way is to declare it as a dependency (eg., `http_file`) in the Bazel workspace.

The challenge in doing so is that Cargo Raze is distributed as a crate package, not binary. Therefore we have to find a way to have it downloaded and compiled in the local machine (e.g, by using `rust_binary`).

**Comment by alexjpwalker** [comment] 2022-07-08 16:19
duplicate of https://github.com/vaticle/dependencies/issues/321

**Closed by alexjpwalker** 2022-07-08 16:19 UTC
Labels: type: feature, priority: high
